8959: Remove redundant python-gflags fpm-info.sh.
I added this file in 495a485ff.  Later, Nico pinned the version in
run-build-packages, in a8bbf6ef, to try to fix #8959.  However, odds
are that #8959 was an ops problem, and not a package building problem:
the gflags 3.0 packages were still published on our repository, and
needed to be removed there.

Having both files causes trouble when you're building backports from
scratch.  We haven't noticed because Jenkins never does that.  But
I'm working on new packages and getting:

    Loading fpm overrides from /arvados/backports/python-gflags/fpm-info.sh

    fpm --maintainer=Ward Vandewege <ward@curoverse.com> -s python -t rpm --exclude=*/dist-packages/tests/* --exclude=*/site-packages/tests/* --verbose --log info -n python-gflags --iteration 1 --python-bin python2.7 --python-easyinstall easy_install-2.7 --python-package-name-prefix python --depends python -v 2.0 python-gflags==2.0

    Error: python-gflags==2.0: Unable to figure out package name from fpm results:

    {:timestamp=>"2016-05-27T22:20:53.045329+0000", :message=>"Setting workdir", :workdir=>"/tmp", :level=>:info} {:timestamp=>"2016-05-27T22:20:53.049435+0000", :message=>"Trying to download", :package=>"python-gflags==2.0", :level=>:info} {:timestamp=>"2016-05-27T22:20:53.122897+0000", :message=>"error: Not a URL, existing file, or requirement spec: 'python-gflags==2.0==2.0'", :level=>:info} {:timestamp=>"2016-05-27T22:20:53.130325+0000", :message=>"Process failed: easy_install-2.7 failed (exit code 1). Full command was:[\"easy_install-2.7\", \"-i\", \"https://pypi.python.org/simple\", \"--editable\", \"-U\", \"--build-directory\", \"/tmp/package-python-build20160527-1643-3sl5ec/python-gflags==2.0\", \"python-gflags==2.0==2.0\"]", :level=>:error}

Refs #8959.