Bump cwltool dependency. Previously pinned version was broken.
cwltool==1.0.20160630171631 depends on
schema-salad==1.12.20160610104117, which contains an errant .py file
with syntax errors. Installing with pip emits an error message and
succeeds. Installing as an fpm->deb package emits the same error
message and fails.

Linking and byte-compiling packages for runtime python2.7...
  File "/usr/lib/python2.7/dist-packages/schema_salad/ref_resolver_BACKUP_28804.py", line 222
      <<<<<<< 973dceb3aeef33920968fa257c7b04885a3a716d
           ^
           SyntaxError: invalid syntax

No issue #