Render token with ApplicationController#show instead of calling as_api_response directly from api_client_authorizations.create_system_auth.
Resolves:

Error: #<ActsAsApi::TemplateNotFoundError: acts_as_api template
:superuser was not found for model ApiClientAuthorization>