20300: Call safe_load explicitly instead of using safe_yaml gem.
safe_yaml breaks new i18n.

ArgumentError: wrong number of arguments (given 2, expected 1)
/home/tom/.gem/ruby/2.7.0/gems/safe_yaml-1.0.5/lib/safe_yaml.rb:37:in `unsafe_load_file'
/home/tom/.gem/ruby/2.7.0/gems/i18n-1.14.1/lib/i18n/backend/base.rb:254:in `load_yml'
...

Arvados-DCO-1.1-Signed-off-by: Tom Clegg <tom@curii.com>