libcloud 2.3.0 now requires python-requests 2.4.3 or higher, otherwise it throws
  ImportError: No module named packages.urllib3.poolmanager

when loaded. We only see this problem on ubuntu1404, because that is our
only supported distribution that ships with a python-requests older than
2.4.3. This issue was caught by our automated package testing, yay!

No issue #

Arvados-DCO-1.1-Signed-off-by: Ward Vandewege <wvandewege@veritasgenetics.com>