Add libwww-perl and python mock dependencies, so tests can run on ubuntu 14.04
If we let setuptools install mock for us (because it's listed in
tests_require), "python setup.py test" fails:

running test
Searching for mock>=1.0
Best match: mock 1.3.0
Processing mock-1.3.0-py2.7.egg

Using /tmp/arvados/sdk/python/.eggs/mock-1.3.0-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    cmdclass={'egg_info': tagger},
[...]
  File "/tmp/.cache/arvados-build/VENVDIR/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2910, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pkg_resources.RequirementParseError: Expected version spec in funcsigs;python_version<"3.3" at ;python_version<"3.3

No issue #