Install bundler gem in all build containers.
RVM used to install bundler by default, but now it doesn't.

https://github.com/rvm/rvm/commit/dc07790042d78c525d7d52616c78cb2d55c0e764

I suppose some systems (like Jenkins) have been able to continue
working because they have cached docker images that were built before
RVM dropped bundler (1.26.11 -- Mar 30, 2015).

But on a new system, we ended up here:

[...]
Package python3-websocket-client_0.35.0-1_all.deb exists, not rebuilding
/jenkins/run-library.sh: line 139: bundle: command not found
ERROR: arvados-api-server package prep failed
/jenkins/run-build-packages.sh: line 492: bundle: command not found
ERROR: Asset precompilation failed
ERROR:  build failed with exit status 1.

No issue #